/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuotationRouteImport } from './routes/quotation'
import { Route as PlaceOrderRouteImport } from './routes/place-order'
import { Route as PendingsRouteImport } from './routes/pendings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuotationsIndexRouteImport } from './routes/quotations.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as QuotationsQuoteIdRouteImport } from './routes/quotations.$quoteId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationRoute = QuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceOrderRoute = PlaceOrderRouteImport.update({
  id: '/place-order',
  path: '/place-order',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingsRoute = PendingsRouteImport.update({
  id: '/pendings',
  path: '/pendings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsIndexRoute = QuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsQuoteIdRoute = QuotationsQuoteIdRouteImport.update({
  id: '/quotations/$quoteId',
  path: '/quotations/$quoteId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pendings': typeof PendingsRoute
  '/place-order': typeof PlaceOrderRoute
  '/quotation': typeof QuotationRoute
  '/settings': typeof SettingsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/quotations/$quoteId': typeof QuotationsQuoteIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pendings': typeof PendingsRoute
  '/place-order': typeof PlaceOrderRoute
  '/quotation': typeof QuotationRoute
  '/settings': typeof SettingsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/quotations/$quoteId': typeof QuotationsQuoteIdRoute
  '/orders': typeof OrdersIndexRoute
  '/quotations': typeof QuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pendings': typeof PendingsRoute
  '/place-order': typeof PlaceOrderRoute
  '/quotation': typeof QuotationRoute
  '/settings': typeof SettingsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/quotations/$quoteId': typeof QuotationsQuoteIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pendings'
    | '/place-order'
    | '/quotation'
    | '/settings'
    | '/orders/$orderId'
    | '/quotations/$quoteId'
    | '/orders/'
    | '/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pendings'
    | '/place-order'
    | '/quotation'
    | '/settings'
    | '/orders/$orderId'
    | '/quotations/$quoteId'
    | '/orders'
    | '/quotations'
  id:
    | '__root__'
    | '/'
    | '/pendings'
    | '/place-order'
    | '/quotation'
    | '/settings'
    | '/orders/$orderId'
    | '/quotations/$quoteId'
    | '/orders/'
    | '/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PendingsRoute: typeof PendingsRoute
  PlaceOrderRoute: typeof PlaceOrderRoute
  QuotationRoute: typeof QuotationRoute
  SettingsRoute: typeof SettingsRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  QuotationsQuoteIdRoute: typeof QuotationsQuoteIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  QuotationsIndexRoute: typeof QuotationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation': {
      id: '/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof QuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place-order': {
      id: '/place-order'
      path: '/place-order'
      fullPath: '/place-order'
      preLoaderRoute: typeof PlaceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendings': {
      id: '/pendings'
      path: '/pendings'
      fullPath: '/pendings'
      preLoaderRoute: typeof PendingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/': {
      id: '/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof QuotationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/$quoteId': {
      id: '/quotations/$quoteId'
      path: '/quotations/$quoteId'
      fullPath: '/quotations/$quoteId'
      preLoaderRoute: typeof QuotationsQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PendingsRoute: PendingsRoute,
  PlaceOrderRoute: PlaceOrderRoute,
  QuotationRoute: QuotationRoute,
  SettingsRoute: SettingsRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  QuotationsQuoteIdRoute: QuotationsQuoteIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  QuotationsIndexRoute: QuotationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
