/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuotationRouteImport } from './routes/quotation'
import { Route as PlaceOrderRouteImport } from './routes/place-order'
import { Route as PendingsRouteImport } from './routes/pendings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders_.$orderId'

const QuotationRoute = QuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceOrderRoute = PlaceOrderRouteImport.update({
  id: '/place-order',
  path: '/place-order',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingsRoute = PendingsRouteImport.update({
  id: '/pendings',
  path: '/pendings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders_/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/pendings': typeof PendingsRoute
  '/place-order': typeof PlaceOrderRoute
  '/quotation': typeof QuotationRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/pendings': typeof PendingsRoute
  '/place-order': typeof PlaceOrderRoute
  '/quotation': typeof QuotationRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/pendings': typeof PendingsRoute
  '/place-order': typeof PlaceOrderRoute
  '/quotation': typeof QuotationRoute
  '/orders_/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orders'
    | '/pendings'
    | '/place-order'
    | '/quotation'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orders'
    | '/pendings'
    | '/place-order'
    | '/quotation'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/orders'
    | '/pendings'
    | '/place-order'
    | '/quotation'
    | '/orders_/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrdersRoute: typeof OrdersRoute
  PendingsRoute: typeof PendingsRoute
  PlaceOrderRoute: typeof PlaceOrderRoute
  QuotationRoute: typeof QuotationRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quotation': {
      id: '/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof QuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place-order': {
      id: '/place-order'
      path: '/place-order'
      fullPath: '/place-order'
      preLoaderRoute: typeof PlaceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendings': {
      id: '/pendings'
      path: '/pendings'
      fullPath: '/pendings'
      preLoaderRoute: typeof PendingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/$orderId': {
      id: '/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrdersRoute: OrdersRoute,
  PendingsRoute: PendingsRoute,
  PlaceOrderRoute: PlaceOrderRoute,
  QuotationRoute: QuotationRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
